chore: add `OdisPayments` address
celo-org/docs pull request #1247
Opened 2024-02-19 10:50 UTC by therealharpaljadeja

2024-04-02 09:41 UTC, GigaHierz requested changes
Please add explanation/ link for addition of address

2024-04-02 13:10 UTC, therealharpaljadeja commented
> Please add explanation/ link for addition of address

The PR is to add an address only, an explanation for the same is in the SocialConnect repo.

2024-04-02 19:40 UTC, GigaHierz approved these changes

2024-04-03 18:14 UTC, merged

2024-09-28 13:32 UTC, SamyDgz reviewed
@SamyDGZ