updated dev resources branch with main updates to merge with main
celo-org/docs pull request #1500
Opened 2024-09-26 22:35 UTC by sodofi

2024-10-01 09:15 UTC, lvpeschke approved these changes

2024-10-01 09:15 UTC, lvpeschke commented on docs/developer/explorers/block-explorers.md
> +Blockscout explorer is available for <ColoredText>[Celo](https://explorer.celo.org/mainnet/blocks)</ColoredText>. If your contract is verfied on Blockscout, you can interact with and debug smart cont
```suggestion
Blockscout explorer is available for <ColoredText>[Celo](https://celo.blockscout.com)</ColoredText>. If your contract is verfied on Blockscout, you can interact with and debug smart contracts.
```

2024-10-01 09:17 UTC, lvpeschke commented
Note: I did not review every page, relying on the other reviewers to have a look here.

2024-10-01 10:59 UTC, lvpeschke commented on docs/build/add-celo-testnet-to-metamask.md
> +Follow this quick guide to add Dango to your MetaMask wallet and start playing around with it. You can get funds from the [Alfajores Faucet](https://faucet.celo.org).
```suggestion
Follow this quick guide to add Alfajores to your MetaMask wallet and start playing around with it. You can get funds from the [Alfajores Faucet](https://faucet.celo.org).
```

2024-10-04 15:02 UTC, aaronmgdr commented on docs/build/add-celo-testnet-to-metamask.md
> +- Block explorer URL: `https://explorer.celo.org/alfajores`
```suggestion
- Block explorer URL: `https://celo-alfajores.blockscout.com`

2024-10-04 15:03 UTC, aaronmgdr commented on docs/build/build-on-minipay/code-library.mdx
> +        npm install @celo/abis @celo/identity viem@1
```suggestion
        npm install @celo/abis @celo/identity viem@2

2024-10-04 15:08 UTC, aaronmgdr commented on docs/build/how-to-deploy/verify/celo-explorer.md
> +title: Verify with Celo Explorer
this should be replace with blockscout verifiucation page.

2024-10-04 15:10 UTC, aaronmgdr commented on docs/build/integrations/guide.md
> +### Identity Protocol
call this Social Connect

2024-10-04 15:12 UTC, aaronmgdr commented on docs/build/integrations/guide.md
> +When transferring assets, wallets should check the receiving account's `walletAddress`. Smart contract accounts may have different recovery characteristics but receive funds at a different address. A
i dont think this is really true

2024-10-04 15:13 UTC, aaronmgdr requested changes
45 pages and not even a description. can we do better?

2024-10-04 15:24 UTC, aaronmgdr commented
remember that sweet bridging page @therealharpaljadeja made for the dango launch? lets bring that back

2024-10-04 15:31 UTC, aaronmgdr commented on docs/build/integrations/guide.md
> +Celo wallets should follow [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) for deriving private keys from [BIP39 mnemonics](https://github.com/bitcoin/bips/blob/master/bip-003
note to self about derivation key standard. re defaulting to ethereum

2024-11-06 05:17 UTC, closed without merging