Sage/getting-started-on-celo-with-hardhat
celo-org/docs pull request #509
Opened 2022-12-08 17:19 UTC by bobeu

Tutorial completed!

2022-12-14 15:46 UTC, viral-sangani requested changes

2022-12-14 15:46 UTC, viral-sangani commented on blog/08-12-22-getting-started-on-celo-with-hardhat/gettng-started-on-celo-with-hardhat.md
> +![image](images/4.png)
Add a new line for the image.

2022-12-14 15:46 UTC, viral-sangani commented on blog/08-12-22-getting-started-on-celo-with-hardhat/gettng-started-on-celo-with-hardhat.md
> +`Note`: Hardhat will always perform a new compilation instruction if changes to previously compiled contract (s) exist. This is done using the cache file that will be generated soon as hardhat comman
```suggestion
> Note: Hardhat will always perform a new compilation instruction if changes to previously compiled contract (s) exist. This is done using the cache file that will be generated soon as hardhat command is invoked.
```

2022-12-14 15:46 UTC, viral-sangani commented on blog/08-12-22-getting-started-on-celo-with-hardhat/gettng-started-on-celo-with-hardhat.md
> +`Note`: If you run `'npx hardhat'` using Bash CLI, you get a weird error like this.
```suggestion

> Note: If you run `'npx hardhat'` using Bash CLI, you get a weird error like this.
```

2022-12-14 15:46 UTC, viral-sangani commented
@bobeu I have requested some minor changes. Can you please review this?

2022-12-14 20:00 UTC, bobeu commented on blog/08-12-22-getting-started-on-celo-with-hardhat/gettng-started-on-celo-with-hardhat.md
> +![image](images/4.png)
Resolved

2022-12-14 20:22 UTC, bobeu commented on blog/08-12-22-getting-started-on-celo-with-hardhat/gettng-started-on-celo-with-hardhat.md
> +![image](images/4.png)
Fixed

2022-12-15 05:28 UTC, viral-sangani approved these changes

2022-12-15 05:29 UTC, viral-sangani commented
LGTM.
@bobeu Congratulations on completing this article. 🎉

2022-12-15 05:29 UTC, merged

2022-12-15 19:20 UTC, bobeu commented
> LGTM. @bobeu Congratulations on completing this article. 🎉

Thank you @viral-sangani